# Configuration PubSub DevTools
# Fichier de configuration centralisé pour tous les services

# === Répertoires Communs (Exemples) ===
# Ces chemins sont utilisés par les services si non surchargés ci-dessous.
# Ils pointent vers des exemples internes au projet DevTools.
agents_dir: "./examples/sample_project/agents"
events_dir: "./examples/sample_project/events"
recordings_dir: "./recordings"
cache_dir: "./.cache"
replay_data_dir: "./replay_data"
scenarios_dir: "./examples/sample_project/scenarios"
reports_dir: "./reports"

# === Configurations par service ===

event_flow:
  # Les chemins agents_dir et events_dir ne sont plus nécessaires ici.
  # Le scanner les fournira directement à l'API.
  port: 5555
  test_agents:
    - "token_balance_refresh"

event_recorder:
  recordings_dir: "./recordings"
  port: 5556

mock_exchange:
  port: 5557
  default_initial_price: 50000.0
  default_volatility: 0.02
  default_spread_bps: 10.0

scenario_testing:
  scenarios_dir: "./examples/sample_project/scenarios" # Champ obligatoire ajouté
  reports_dir: "./reports"
  port: 5558
