# PubSub Dev Tools Configuration Example
#
# Copy this file to your project root and customize paths for your project

# Project paths - adjust these to match your project structure
agents_dir: "python_pubsub_risk/agents"
events_dir: "python_pubsub_risk/events"
recordings_dir: "tools/event_recorder/recordings"
scenarios_dir: "tools/scenario_testing/scenarios"
reports_dir: "tools/scenario_testing/reports"

# Event Flow Visualization
event_flow:
  port: 5555

  # Agents to exclude from visualization (test/utility agents)
  test_agents:
    - "token_balance_refresh"

  # Namespace colors for event categorization
  namespace_colors:
    bot_lifecycle: "#81c784"    # green
    market_data: "#64b5f6"      # blue
    indicator: "#9575cd"        # purple
    internal: "#ba68c8"         # purple light
    capital: "#ffd54f"          # yellow
    pool: "#ffb74d"             # orange
    position: "#ff8a65"         # deep orange
    exchange: "#4dd0e1"         # cyan
    command: "#a1887f"          # brown
    database: "#90a4ae"         # blue grey
    exit_strategy: "#aed581"   # light green
    query: "#81d4fa"            # light blue
    unknown: "#e0e0e0"          # grey

# Event Recorder
event_recorder:
  port: 5556

# Mock Exchange Simulator
mock_exchange:
  port: 5557
  default_initial_price: 50000.0
  default_volatility: 0.02
  default_spread_bps: 10.0

# Scenario Testing
scenario_testing:
  port: 5558