# Configuration PubSub DevTools
# Fichier de configuration centralisé pour tous les services

# === Répertoires Communs ===
# Chemins relatifs (par rapport à ce fichier) ou absolus
# NOTE: Ajustez ces chemins pour correspondre à votre structure de projet
agents_dir: "../path/to/your/agents"
events_dir: "../path/to/your/events"
recordings_dir: "./recordings"
scenarios_dir: "./scenarios"
reports_dir: "./reports"

# === Event Flow Visualization ===
event_flow:
  port: 5555

  # Agents à exclure de la visualisation (agents de test/utilitaires)
  test_agents:
    - "token_balance_refresh"

  # Couleurs par namespace pour la catégorisation
  namespace_colors:
    bot_lifecycle: "#81c784"    # vert
    market_data: "#64b5f6"      # bleu
    indicator: "#9575cd"        # violet
    internal: "#ba68c8"         # violet clair
    capital: "#ffd54f"          # jaune
    pool: "#ffb74d"             # orange
    position: "#ff8a65"         # orange foncé
    exchange: "#4dd0e1"         # cyan
    command: "#a1887f"          # marron
    database: "#90a4ae"         # gris bleu
    exit_strategy: "#aed581"    # vert clair
    query: "#81d4fa"            # bleu clair
    unknown: "#e0e0e0"          # gris

# === Event Recorder ===
event_recorder:
  port: 5556

# === Mock Exchange Simulator ===
mock_exchange:
  port: 5557
  default_initial_price: 50000.0
  default_volatility: 0.02
  default_spread_bps: 10.0

# === Scenario Testing ===
scenario_testing:
  port: 5558

# === Instructions d'Utilisation ===
#
# 1. Copiez ce fichier dans le répertoire racine de votre projet
# 2. Ajustez les chemins vers vos répertoires agents/ et events/
# 3. Lancez les services avec:
#
#    CLI:
#      pubsub-tools event-flow --config devtools_config.yaml
#      pubsub-tools event-recorder --config devtools_config.yaml
#      pubsub-tools mock-exchange --config devtools_config.yaml
#      pubsub-tools scenario-testing --config devtools_config.yaml
#      pubsub-tools serve-all --config devtools_config.yaml
#
#    Python (API programmatique):
#      from python_pubsub_devtools.config import DevToolsConfig
#      from python_pubsub_devtools.event_flow.server import EventFlowServer
#
#      config = DevToolsConfig.from_yaml("devtools_config.yaml")
#      server = EventFlowServer(config.event_flow)
#      server.run()  # Bloquant
#
# === Structure de Répertoires Recommandée ===
# votre-projet/
# ├── devtools_config.yaml  # Ce fichier
# ├── agents/               # Fichiers Python des agents
# │   ├── market_agent.py
# │   ├── risk_agent.py
# │   └── execution_agent.py
# ├── events/               # Fichiers JSON des événements
# │   ├── MarketDataReceived.json
# │   ├── RiskAssessed.json
# │   └── OrderExecuted.json
# ├── recordings/           # Sessions d'enregistrement (créé automatiquement)
# ├── scenarios/            # Scénarios de test YAML (optionnel)
# └── reports/              # Rapports de tests (créé automatiquement)
